Adding linux cli
OctopusDeploy/Octopus.Dependencies.TerraformCLI pull request #3
Opened 2018-12-03 02:19 UTC by johnsimons

Updating packages on every build

2018-12-03 03:27 UTC, benPearce1 requested changes

2018-12-03 03:27 UTC, benPearce1 commented on build.cake
> +        foreach (var pluginName in new[] {"terraform-provider-azurerm", "terraform-provider-aws", "terraform-provider-azure"})
As well as the latest this should also pick up the existing versions that we were previously shipping (e.g. azure rm 1.13, 1.16 and 1.17). Hosted doesn't currently allow terraform providers to be downloaded as required, the workaround was to hard-code the provider version number into the terraform template. If we drop those provider versions it will fail on hosted where the version number has been specified.

2018-12-03 03:31 UTC, johnsimons commented on build.cake
> +        foreach (var pluginName in new[] {"terraform-provider-azurerm", "terraform-provider-aws", "terraform-provider-azure"})
it feels like we are adding an edge case for hosted

2018-12-03 03:32 UTC, johnsimons commented on build.cake
> +        foreach (var pluginName in new[] {"terraform-provider-azurerm", "terraform-provider-aws", "terraform-provider-azure"})
to me it feels like if hosted hardcodes versions and does not allow to be d/l then IMO it feels like they should install terraform on the machine ?

2018-12-06 03:22 UTC, benPearce1 approved these changes

2018-12-06 21:56 UTC, merged